### PR TITLE
Update package structure for rstan 2.26 compatibility

### PR DESCRIPTION
**Pull request by andrjohns**
This PR updates your package's installation/configuration to better delegate to `rstantools` for compatibility with the next rstan version.

I've also updated your workflow actions so that the dependencies install, and removed the `R-CMD-test` workflow since the package tests are run as part of the `R CMD CHECK` process

### CODE REVIEW

**Comment by andrjohns** [comment]
Would you be able to merge this PR and release to CRAN? We're aiming to submit a new release of rstan soon

**Comment by FBartos** [comment]
Hi Andrew,

Sorry, this completely slipped through my attention. Thanks for the PR -- I will check and verify in the beginning of the next week.

Cheers,
Frantisek

**Comment by FBartos** [comment]
Thanks @andrjohns , it seems to work,

just two small questions:
- What's the best practice for dealing with the rstantools generated files? (e.g., R/stanmodels.R, src/Makevars, and all the .h and .cc files) Should I include them in the GitHub repo or include them into a gitignore?
- Should I submit this to CRAN already or wait till the new rstan is there?

Thanks,
Frantisek

**Comment by andrjohns** [comment]
Included in a gitignore would be best.

Submitting to CRAN now would be great, thanks!

**Comment by FBartos** [comment]
It's already on its way to CRAN.

Thanks a lot for the modifications, I really appreciate it!

**Pull request merged**
